package com.virgo.com.pc.mapper;

import com.baomidou.mybatisplus.mapper.BaseMapper;
import com.virgo.com.pc.entity.Account;
import java.util.List;

public interface AccountMapper extends BaseMapper<Account> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Account
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Account
     *
     * @mbg.generated
     * @return
     */
    Integer insert(Account record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Account
     *
     * @mbg.generated
     */
    Account selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Account
     *
     * @mbg.generated
     */
    List<Account> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Account
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Account record);
}