package com.virgo.com.pc.mapper;

import com.baomidou.mybatisplus.mapper.BaseMapper;
import com.virgo.com.pc.entity.Miniofile;

import java.util.List;

public interface MiniofileMapper extends BaseMapper<Miniofile> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MinioFile
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MinioFile
     *
     * @mbg.generated
     * @return
     */
    Integer insert(Miniofile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MinioFile
     *
     * @mbg.generated
     */
    Miniofile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MinioFile
     *
     * @mbg.generated
     */
    List<Miniofile> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MinioFile
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Miniofile record);
}