package com.virgo.com.pc.entity;

import com.baomidou.mybatisplus.annotations.TableId;
import com.baomidou.mybatisplus.enums.IdType;
import com.virgo.com.pc.bean.BaseEntity;

import java.io.Serializable;

public class Miniofile extends BaseEntity implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MinioFile.id
     *
     * @mbg.generated  @TableId(value = "id", type = IdType.AUTO)
     */
    @TableId(value = "id", type = IdType.AUTO)
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MinioFile.savename
     *
     * @mbg.generated
     */
    private String savename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MinioFile.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MinioFile.suffix
     *
     * @mbg.generated
     */
    private String suffix;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MinioFile.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MinioFile.createDate
     *
     * @mbg.generated
     */
    private String createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MinioFile.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MinioFile.size
     *
     * @mbg.generated
     */
    private Long size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MinioFile.thumb
     *
     * @mbg.generated
     */
    private String thumb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MinioFile.resolve
     *
     * @mbg.generated
     */
    private String resolve;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MinioFile.duration
     *
     * @mbg.generated
     */
    private Long duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table MinioFile
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MinioFile.id
     *
     * @return the value of MinioFile.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MinioFile.id
     *
     * @param id the value for MinioFile.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MinioFile.savename
     *
     * @return the value of MinioFile.savename
     *
     * @mbg.generated
     */
    public String getSavename() {
        return savename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MinioFile.savename
     *
     * @param savename the value for MinioFile.savename
     *
     * @mbg.generated
     */
    public void setSavename(String savename) {
        this.savename = savename == null ? null : savename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MinioFile.name
     *
     * @return the value of MinioFile.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MinioFile.name
     *
     * @param name the value for MinioFile.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MinioFile.suffix
     *
     * @return the value of MinioFile.suffix
     *
     * @mbg.generated
     */
    public String getSuffix() {
        return suffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MinioFile.suffix
     *
     * @param suffix the value for MinioFile.suffix
     *
     * @mbg.generated
     */
    public void setSuffix(String suffix) {
        this.suffix = suffix == null ? null : suffix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MinioFile.url
     *
     * @return the value of MinioFile.url
     *
     * @mbg.generated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MinioFile.url
     *
     * @param url the value for MinioFile.url
     *
     * @mbg.generated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MinioFile.createDate
     *
     * @return the value of MinioFile.createDate
     *
     * @mbg.generated
     */
    public String getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MinioFile.createDate
     *
     * @param createdate the value for MinioFile.createDate
     *
     * @mbg.generated
     */
    public void setCreatedate(String createdate) {
        this.createdate = createdate == null ? null : createdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MinioFile.type
     *
     * @return the value of MinioFile.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MinioFile.type
     *
     * @param type the value for MinioFile.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MinioFile.size
     *
     * @return the value of MinioFile.size
     *
     * @mbg.generated
     */
    public Long getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MinioFile.size
     *
     * @param size the value for MinioFile.size
     *
     * @mbg.generated
     */
    public void setSize(Long size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MinioFile.thumb
     *
     * @return the value of MinioFile.thumb
     *
     * @mbg.generated
     */
    public String getThumb() {
        return thumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MinioFile.thumb
     *
     * @param thumb the value for MinioFile.thumb
     *
     * @mbg.generated
     */
    public void setThumb(String thumb) {
        this.thumb = thumb == null ? null : thumb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MinioFile.resolve
     *
     * @return the value of MinioFile.resolve
     *
     * @mbg.generated
     */
    public String getResolve() {
        return resolve;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MinioFile.resolve
     *
     * @param resolve the value for MinioFile.resolve
     *
     * @mbg.generated
     */
    public void setResolve(String resolve) {
        this.resolve = resolve == null ? null : resolve.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MinioFile.duration
     *
     * @return the value of MinioFile.duration
     *
     * @mbg.generated
     */
    public Long getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MinioFile.duration
     *
     * @param duration the value for MinioFile.duration
     *
     * @mbg.generated
     */
    public void setDuration(Long duration) {
        this.duration = duration;
    }

    @Override
    public int getRowId() {
        return getId();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MinioFile
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", savename=").append(savename);
        sb.append(", name=").append(name);
        sb.append(", suffix=").append(suffix);
        sb.append(", url=").append(url);
        sb.append(", createdate=").append(createdate);
        sb.append(", type=").append(type);
        sb.append(", size=").append(size);
        sb.append(", thumb=").append(thumb);
        sb.append(", resolve=").append(resolve);
        sb.append(", duration=").append(duration);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}